id: swagger-api

info:
  name: Public Swagger API - Detect
  author: pdteam,c-sh0,AmirHossein Raeisi
  severity: info
  description: Public Swagger API was detected.
  reference: https://swagger.io/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  tags: exposure,api,swagger

http:
  - method: GET
    path:
      - "{{BaseURL}}{{paths}}"

    payloads:
      paths:
        - "/__swagger__/"
        - "/_swagger_/"
        - "/api-doc"
        - "/api-docs/swagger.json"
        - "/api-docs/swagger.yaml"
        - "/api-docs/v1/swagger.json"
        - "/api-docs/v2/swagger.json"
        - "/api-docs/v3/swagger.json"
        - "/api/__swagger__/"
        - "/api/_swagger_/"
        - "/api/api-docs"
        - "/api/api-docs/swagger.json"
        - "/api/api-docs/swagger.yaml"
        - "/api/apidocs"
        - "/api/apidocs/swagger.json"
        - "/api/apidocs/swagger.yaml"
        - "/api/doc"
        - "/api/doc.json"
        - "/api/docs/"
        - "/api/index.html"
        - "/api/openapi.json"
        - "/api/spec/swagger.json"
        - "/api/spec/swagger.yaml"
        - "/api/swagger"
        - "/api/swagger-resources"
        - "/api/swagger-resources/restservices/v2/api-docs"
        - "/api/swagger-ui.html"
        - "/api/swagger-ui/api-docs"
        - "/api/swagger-ui/swagger.json"
        - "/api/swagger-ui/swagger.yaml"
        - "/api/swagger.json"
        - "/api/swagger.yaml"
        - "/api/swagger.yml"
        - "/api/swagger/index.html"
        - "/api/swagger/static/index.html"
        - "/api/swagger/swagger-ui-init.js"
        - "/api/swagger/swagger-ui.html"
        - "/api/swagger/ui/index"
        - "/api/swagger/v1/swagger.json"
        - "/api/swagger/v2/swagger.json"
        - "/api/swagger/v3/swagger.json"
        - "/api/swagger_doc.json"
        - "/api/v1/openapi.json"
        - "/api/v1/swagger-ui/swagger.json"
        - "/api/v1/swagger-ui/swagger.yaml"
        - "/api/v1/swagger/swagger-ui-init.js"
        - "/api/v1/swagger/swagger.json"
        - "/api/v2/openapi.json"
        - "/api/v3/openapi.json"
        - "/api_docs"
        - "/developers/documentation"
        - "/doc/"
        - "/docs"
        - "/docs/"
        - "/docs/openapi.json"
        - "/docs/swagger.json"
        - "/docs/v1/openapi.json"
        - "/docs/v1/swagger.json"
        - "/docs/v2/openapi.json"
        - "/docs/v2/swagger.json"
        - "/docs/v3/openapi.json"
        - "/docs/v3/swagger.json"
        - "/docu"
        - "/openapi.json"
        - "/swagger"
        - "/swagger-resources/restservices/v2/api-docs"
        - "/swagger-ui-init.js"
        - "/swagger-ui.html"
        - "/swagger-ui.js"
        - "/swagger-ui/springfox.js"
        - "/swagger-ui/swagger-ui-standalone-preset.js"
        - "/swagger-ui/swagger-ui.js"
        - "/swagger-ui/swagger-ui/swagger-ui-bundle.js"
        - "/swagger.json"
        - "/swagger.json"
        - "/swagger.yaml"
        - "/swagger/index.html"
        - "/swagger/swagger-ui-init.js"
        - "/swagger/swagger-ui.html"
        - "/swagger/swagger-ui.js"
        - "/swagger/ui/index"
        - "/swagger/ui/swagger-ui.js"
        - "/swagger/v1/swagger.json"
        - "/swagger/v1/swagger.yaml"
        - "/swagger/v2/swagger.json"
        - "/swagger/v3/swagger.json"
        - "/v1/openapi.json"
        - "/v2/openapi.json"
        - "/v3/openapi.json"
        - "/webjars/swagger-ui/index.html"
        - "/webjars/swagger-ui/swagger-ui-bundle.js"
        
    headers:
      Accept: text/html

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "swagger:"
          - "Swagger 2.0"
          - "\"swagger\":"
          - "Swagger UI"
          - "loadSwaggerUI"
          - "**token**:"
          - "id=\"swagger-ui"
          - "swaggerDoc"
        condition: or

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - " @version (v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})"
          
      - type: regex
        part: body
        name: jwt
        group: 0
        regex:
          - "eyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9._-]+\\.[A-Za-z0-9._-]+"
